[package]
name = "rust-dimensional-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
polars-core = "0.46.0"
polars-io = { version = "0.46.0", features = ["csv", "fmt"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
zip = "2.2.2"
