[package]
name = "rust-dimensional-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46.0", features = ["csv"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
